// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLvCFzU2dRC7c_wFUuCT5dbhLVpBb3eo',
    appId: '1:1008496453558:web:f9fd71289201c72e6ac317',
    messagingSenderId: '1008496453558',
    projectId: 'chat-e342b',
    authDomain: 'chat-e342b.firebaseapp.com',
    storageBucket: 'chat-e342b.firebasestorage.app',
    measurementId: 'G-WJXY08DPK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dHOEqarQJn3EfwKHOJoqMaRqDpV24J8',
    appId: '1:1008496453558:android:e8366c1db27beb306ac317',
    messagingSenderId: '1008496453558',
    projectId: 'chat-e342b',
    storageBucket: 'chat-e342b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3JMGkwz90B4JPkPq7E4FzKnAyZdfexc',
    appId: '1:1008496453558:ios:116c3dbe4c8d81996ac317',
    messagingSenderId: '1008496453558',
    projectId: 'chat-e342b',
    storageBucket: 'chat-e342b.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-3JMGkwz90B4JPkPq7E4FzKnAyZdfexc',
    appId: '1:1008496453558:ios:116c3dbe4c8d81996ac317',
    messagingSenderId: '1008496453558',
    projectId: 'chat-e342b',
    storageBucket: 'chat-e342b.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPLvCFzU2dRC7c_wFUuCT5dbhLVpBb3eo',
    appId: '1:1008496453558:web:daa8c0a3274a3a796ac317',
    messagingSenderId: '1008496453558',
    projectId: 'chat-e342b',
    authDomain: 'chat-e342b.firebaseapp.com',
    storageBucket: 'chat-e342b.firebasestorage.app',
    measurementId: 'G-5NG71PYMVE',
  );
}
